# Brewfile
cask_args appdir: "/Applications"
tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"

brew "vim"
brew "zsh"
brew "zsh-completions"
brew "nkf"
brew "ruby"
brew "rbenv"
brew "redis"
brew "webp"
brew "wget"
brew "jpeg"
brew "jp"
brew "curl"
brew "git"

cask "iterm2"
cask "alfred"
cask "dropbox"
cask "evernote"
cask "google-japanese-ime"
cask "licecap"
cask "sequel-pro"
cask "skitch"
cask "visual-studio-code"
